Базовая структура для typescript
codex-team/codex.collaboration pull request #2
Opened 2019-11-22 05:55 UTC by Dronicho

Добавил typescript, webpack, eslint

2019-11-29 17:53 UTC, gohabereg requested changes

2019-11-29 17:53 UTC, gohabereg commented on src/index.ts
> +function greeter(person: string) {
Убери все из файла, чтобы потом лишних изменений не было

2019-11-29 17:53 UTC, gohabereg commented on dist/index.html
> +    <button id="test">Hello</button>
Это лучше убрать

2019-11-29 17:53 UTC, gohabereg commented on dist/bundle.js
> +/******/ (function(modules) { // webpackBootstrap
Сборку надо выпилить

2019-11-30 11:04 UTC, gohabereg approved these changes

2019-12-02 05:12 UTC, neSpecc requested changes

2019-12-02 05:12 UTC, neSpecc commented on package.json
> +  "author": "Codex Team",
```suggestion
  "author": "CodeX",
```

2019-12-02 05:12 UTC, neSpecc commented on package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.0.1",
```

2019-12-02 05:12 UTC, neSpecc commented on package.json
> +    "url": "https://github.com/Dronicho/codex.collaboration/issues"
```suggestion
    "url": "https://github.com/codex-team/codex.collaboration/issues"
```

2019-12-02 05:12 UTC, neSpecc commented on package.json
> +  "homepage": "https://github.com/Dronicho/codex.collaboration#readme",
```suggestion
  "homepage": "https://github.com/codex-team/codex.collaboration",
```

2019-12-02 05:12 UTC, neSpecc commented on package.json
> +    "url": "git+https://github.com/Dronicho/codex.collaboration.git"
```suggestion
    "url": "git+https://github.com/codex-team/codex.collaboration.git"
```

2019-12-02 05:12 UTC, neSpecc commented on webpack.config.js
> +                            loader: 'babel-loader',
нам точно нужен сейчас babel? может пока выпилить его?

2019-12-02 05:12 UTC, neSpecc commented on webpack.config.js
> +            extensions: ['.js', '.ts', '.tsx']
tsx у нас не используется

2019-12-02 05:12 UTC, neSpecc commented on .gitignore
> +.nuxt
из игнора надо выпилить все, что не используется в проекте

2019-12-04 01:09 UTC, Dronicho commented on webpack.config.js
> +                            loader: 'babel-loader',
А какой смысл его убирать на пару коммитов?
```suggestion
                            loader: 'babel-loader',
```

2019-12-04 14:17 UTC, neSpecc approved these changes

2019-12-04 14:23 UTC, merged